language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "tonvanbart-github"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/.cache'

script:
  - ./gradlew sonarqube -Dsonar.organization=tonvanbart-github -Dsonar.host.url=https://sonarcloud.io